/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#include "dds/DdsDcpsCore.idl"

module ovidds {

  @topic
  struct Frame {
    @key long source_id;
    long count;
    long type;
    long format;
    long size_x;
    long size_y;
    DDS::OctetSeq data;
  };

  @topic
  struct ROI {
    @key long source_id;
    long frame_source_id;
    long count;
    long type;
    long off_x;
    long off_y;
    long size_x;
    long size_y;
  };
};
